# Generated by Django 3.2.5 on 2021-07-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210713_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Purchase', 'Purchase')], max_length=50),
        ),
    ]
