# Generated by Django 3.2.5 on 2021-07-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ready to checkout', 'Ready to checkout'), ('Payment Pending', 'Payment Pending'), ('Payment Completed', 'Payment Completed'), ('Order Placed', 'Order Placed'), ('Order Shipped', 'Order Shipped'), ('Delivered', 'Delivered')], max_length=50),
        ),
    ]
