# Generated by Django 3.2.5 on 2021-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ready to checkout', 'Ready to checkout'), ('Payment Pending', 'Payment Pending'), ('Payment Completed', 'Payment Completed'), ('Order Placed', 'Order Placed'), ('Order Shipped', 'Order Shipped'), ('Delivered', 'Delivered')], default='Ready to checkout', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('E-Wallet', 'E-Wallet'), ('Net Banking', 'Net Banking'), ('Cash on Delivery', 'Cash on Delivery')], default='Credit Card', max_length=50),
        ),
    ]
