# Generated by Django 3.2.6 on 2021-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210815_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street_name',
            field=models.CharField(max_length=50, serialize=False),
        ),
    ]
